### ISSUE TITLE
Right clicking to delete a constraint isn't very clear to user

### ISSUE THREAD

**Issue by pconrad** [n-wach/protractr#1]
Consider how that could be make easier for the user to get.

You might even want to do a "talk aloud" study.   

Here's a primer: https://www.nngroup.com/articles/thinking-aloud-the-1-usability-tool/

You can probably find better source of information, but that will do  as a starting point.

**Comment by n-wach** [comment]
UI has been improved and managing relations is more clear
See commit 6d2fd61adcba35d8cc53a6ec9c917ecac98f058c
